const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = require("./load-app-source")();
const migration = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', '20260826091554_central_audit_log.sql'), 'utf8');
const compactMigration = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', '20260826091911_compact_central_audit_payloads.sql'), 'utf8');
const indexMigration = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', '20260826092040_trim_central_audit_indexes.sql'), 'utf8');
const paginationMigrationName = fs.readdirSync(path.join(__dirname, '..', 'supabase', 'migrations')).find(name=>name.endsWith('_scalable_audit_log_pagination.sql'));
assert.ok(paginationMigrationName,'scalable Audit Log pagination migration is required');
const paginationMigration = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', paginationMigrationName), 'utf8');
const lastPageMigrationName = fs.readdirSync(path.join(__dirname, '..', 'supabase', 'migrations')).find(name=>name.endsWith('_fix_audit_log_last_page_size.sql'));
assert.ok(lastPageMigrationName,'Audit Log last-page remainder migration is required');
const lastPageMigration = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', lastPageMigrationName), 'utf8');
const optimizedMigrationName = fs.readdirSync(path.join(__dirname, '..', 'supabase', 'migrations')).find(name=>name.endsWith('_optimize_rpc_and_representative_history.sql'));
assert.ok(optimizedMigrationName,'RPC retirement migration is required');
const optimizedMigration = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', optimizedMigrationName), 'utf8');

assert.match(migration,/create table if not exists public\.audit_logs/);
assert.match(migration,/alter table public\.audit_logs enable row level security/);
assert.match(migration,/create policy audit_logs_owner_read/);
assert.match(migration,/private\.is_current_owner\(\)/);
assert.match(migration,/revoke all on public\.audit_logs from public,anon,authenticated/);
assert.match(migration,/revoke execute on function public\.get_central_audit_logs\(integer,integer\) from public,anon/);
assert.match(migration,/current_setting\('pepos\.maintenance_reset',true\)='on'/);
assert.doesNotMatch(migration,/delete from public\.audit_logs/,'store reset must preserve existing audit history');
assert.match(migration,/from public\.inventory_count_adjustments/);
assert.match(migration,/from public\.product_unit_changes/);
assert.match(migration,/from private\.inventory_lot_detail_audit/);
assert.match(migration,/where m\.reference_type='lot_reallocation'/);
assert.match(compactMigration,/private\.audit_changed_values/);
assert.match(compactMigration,/private\.audit_identity_snapshot/);
assert.match(compactMigration,/jsonb_object_keys\(v_before\|\|v_after\)/);
assert.match(indexMigration,/drop index if exists public\.idx_audit_logs_entity_occurred/);
assert.match(paginationMigration,/create or replace view private\.central_audit_events_live/);
assert.match(paginationMigration,/create or replace function public\.get_central_audit_log_page/);
assert.match(paginationMigration,/\(event\.occurred_at, event\.event_key\) [<>] \(p_cursor_time, p_cursor_key\)/);
assert.match(paginationMigration,/least\(coalesce\(p_limit, 20\), 100\)/);
assert.match(paginationMigration,/private\.is_current_owner\(\)/);
assert.match(paginationMigration,/revoke all on function public\.get_central_audit_log_page/);
assert.match(paginationMigration,/grant execute on function public\.get_central_audit_log_page[\s\S]*to authenticated/);
assert.match(paginationMigration,/private\.run_data_retention\(5000\)/);
assert.match(lastPageMigration,/v_page_limit integer := v_limit/);
assert.match(lastPageMigration,/mod\(v_total_count, v_limit\)/);
assert.match(lastPageMigration,/limit v_page_limit \+ 1/);
assert.match(optimizedMigration,/drop function if exists public\.get_central_audit_logs\(integer,integer\)/);

assert.match(html,/\['auditlog','AUDIT LOG'/);
assert.match(html,/auditlog: renderAuditLog/);
assert.match(html,/sb\.rpc\('get_central_audit_log_page'/);
assert.doesNotMatch(html,/sb\.rpc\('get_central_audit_logs'/,'AUDIT LOG must not load a fixed 500-row browser snapshot');
assert.match(html,/data-audit-log-page="first"/);
assert.match(html,/กลับไปหน้าแรก/);
assert.match(html,/data-audit-log-page="last"/);
assert.match(html,/ไปหน้าสุดท้าย/);
assert.match(html,/\(tab==='settingsusers'\|\|tab==='auditlog'\)&&user\.owner!==true/);
assert.match(html,/class="audit-log-toolbar" role="search"/);
assert.match(html,/class="audit-log-filter-label">ค้นหาประวัติ/);
assert.match(html,/id="auditLogClearSearch"/);
assert.match(html,/id="auditLogClearFilters"/);
assert.match(html,/\.audit-log-toolbar\{[^}]*linear-gradient/);

console.log('central audit log tests passed');
