const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const file=fs.readdirSync(path.join(root,'supabase/migrations')).find(name=>name.endsWith('_customer_membership_tier_cycles.sql'));
const sql=fs.readFileSync(path.join(root,'supabase/migrations',file),'utf8');
const context=vm.createContext({});
vm.runInContext(app.slice(app.indexOf('function customerTierFromPurchases('),app.indexOf('function customerPurchaseLoad(')),context);
const tier=context.customerTierFromPurchases;
assert.equal(tier(90000,9).label,'ลูกค้าประจำ');
assert.equal(tier(89999.99,9).label,'ลูกค้าทั่วไป');
assert.equal(tier(450000,9).label,'ลูกค้าพิเศษ');
assert.equal(tier(449999.99,9).label,'ลูกค้าประจำ');
assert.equal(tier(0,1).label,'ลูกค้าทั่วไป');
assert.equal(tier(10000,1).label,'ลูกค้าประจำ');
assert.equal(tier(120000,12).average,10000);
assert.equal(tier(600000,12).label,'ลูกค้าพิเศษ');
const progress=context.customerTierProgress;
assert.deepEqual(JSON.parse(JSON.stringify(progress(50000,9))),{tier:{key:'general',label:'ลูกค้าทั่วไป',average:50000/9},remaining:40000,percent:50000/90000*100,nextLabel:'ลูกค้าประจำ'});
assert.equal(progress(90000,9).remaining,360000);
assert.equal(progress(90000,9).nextLabel,'ลูกค้าพิเศษ');
assert.equal(progress(450000,9).percent,100);
assert.equal(progress(450000,9).nextLabel,'');
assert.match(sql,/stable security invoker/i);
assert.match(sql,/auth.uid\(\) is null or not public.can_current_user_page\('contacts'/);
assert.match(sql,/revoke all on function[\s\S]+from public,anon/);
assert.match(sql,/current_timestamp at time zone 'Asia\/Bangkok'/);
assert.match(sql,/loyaltyJoinedAt/);
assert.match(sql,/'membershipCycleTotal'/);
assert.match(sql,/'membershipElapsedMonths'/);
assert.match(sql,/s\.sale_date>=c\.membership_start[\s\S]*s\.sale_date<c\.membership_end[\s\S]*s\.sale_date<=v_today/);
assert.match(sql,/age\(v_today,c\.membership_start\)/);
assert.doesNotMatch(sql,/'currentYearTotal'/);
assert.match(sql,/sum\(s.total\) filter\(where s.status='done'\)/);
assert.match(sql,/s.status in \('done','void'\)/);
assert.match(sql,/s.sale_date>=v_from and s.sale_date<v_until/);
assert.match(sql,/limit 10 offset/);
assert.match(sql,/nullif\(s.data->>'customerId',''\),s.data->'member'->>'id'/);
assert.doesNotMatch(sql,/s\.member\s*=|c\.name\s*=/,'Never associate customers by a mutable/nonunique name');
assert.match(app,/if\(pageKey==='customers'\) pageKey='contacts'/);
const permissionsContext=vm.createContext({activeWarehouseId:1,LEVEL2_HIDDEN_TABS:new Set(['contacts'])});
vm.runInContext(app.slice(app.indexOf('function permissionsForPage('),app.indexOf('function canUseAllWarehousesMode(')),permissionsContext);
assert.equal(permissionsContext.canPerformPageAction('view','customers',{level:2},[]),false);
assert.equal(permissionsContext.canPerformPageAction('view','customers',{level:2},[{page_key:'contacts',warehouse_id:1,can_view:true}]),true);
assert.equal(permissionsContext.canPerformPageAction('view','customers',{level:2},[{page_key:'contacts',warehouse_id:2,can_view:true}]),false);
assert.equal(permissionsContext.canPerformPageAction('edit','customers',{level:2},[{page_key:'contacts',warehouse_id:1,can_view:true,can_edit:false}]),false);
assert.match(app,/customerPurchaseState===state/,'Discard responses from earlier requests');
assert.match(app,/input.focus\(\{preventScroll:true\}\)/,'Async summary refresh must preserve typing focus');
const history=app.slice(app.indexOf('function renderCustomerPurchaseHistory('),app.indexOf('function attachCustomerPurchaseEvents('));
assert.match(history,/value="month"/);assert.match(history,/value="year"/);
assert.doesNotMatch(history,/value="day"|value="range"/);
assert.doesNotMatch(history,/salesHistory\.filter/,'Do not calculate totals from truncated sales cache');
console.log('Customer purchase history and tier boundary tests passed');
