const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.webmanifest'), 'utf8'));
const serviceWorker = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');

assert.match(html, /mobiletools:\s*renderMobileTools/);
assert.match(html, /if\(mobileMode\) currentTab='mobiletools'/);
assert.match(html, /body\.mobile-device-mode \.sidebar,body\.mobile-device-mode \.topbar\{display:none!important/);
assert.match(html, /data-mobile-tool="price"/);
assert.match(html, /data-mobile-tool="inspection"/);
assert.match(html, /data-mobile-tool="stock"/);
assert.match(html, /id="mobileOpenInspectionList"/);
assert.match(html, /id="mobileDeleteInspectionList"/);
assert.match(html, /deleteInspectionListById\(list\.id\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandlePriceCode\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandleInspectionCode,\{continuous:true\}\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandleStockCode,\{continuous:true\}\)/);
assert.match(html, /const continuous=options\.continuous===true/);
assert.match(html, /if\(!continuous\)\{ close\(\); onCode\(value\); return; \}/);
assert.match(html, /ยิงได้หลายสินค้า กด × เมื่อต้องการปิด/);
assert.match(html, /value!==lastValue/);
assert.match(html, /findProductByExactCode\(query\)/);
assert.match(html, /mobileInspectionCheckedSet\(list\.id\)\.add/);
assert.match(html, /id="mobileNewInspectionList"/);
assert.match(html, /function startMobileInspectionDraft\(/);
assert.match(html, /const defaultName=inspectionListDefaultName\(\)/);
assert.match(html, /return `ตรวจสินค้า: \$\{highest\+1\}`/);
assert.match(html, /function addProductToMobileInspectionDraft\(/);
assert.match(html, /inspectionListAddProduct\(product,unitName\)/);
assert.match(html, /id="mobileSaveInspectionDraft"/);
assert.match(html, /data-mobile-draft-add=/);
assert.match(html, /data-mobile-draft-remove=/);
assert.match(html, /function saveMobileInspectionDraft\(/);
assert.match(html, /saveInspectionListDraft\(\)/);
assert.match(html, /function mobileInspectionVisibleLists\(\)/);
assert.match(html, /return inspectionLists\.filter\(list=>!String\(list\?\.stockAdjustedAt\|\|''\)\.trim\(\)\)/);
assert.match(html, /const lists=\[\.\.\.mobileInspectionVisibleLists\(\)\]/);
assert.match(html, /function renderMobileStockEditPanel\(/);
assert.match(html, /id="mobileStockSourceList"/);
assert.match(html, /id="mobileStockImport"/);
assert.match(html, /id="mobileStockInput"/);
assert.match(html, /id="mobileConfirmStockEdit"/);
assert.match(html, /id="mobileToolsRefresh"/);
assert.match(html, /refreshMobileToolsData\(mobileToolsRefresh\)/);
assert.match(html, /await Promise\.all\(\[loadCoreDataFromSupabase\(\),loadInspectionListsFromSupabase\(\)\]\)/);
assert.match(html, /data-mobile-stock-amount=/);
assert.match(html, /data-mobile-stock-unit=/);
const mobileUnitHandlerStart = html.indexOf("document.querySelectorAll('[data-mobile-stock-unit]')");
const mobileAmountHandlerStart = html.indexOf("document.querySelectorAll('[data-mobile-stock-amount]')", mobileUnitHandlerStart);
assert.ok(mobileUnitHandlerStart >= 0 && mobileAmountHandlerStart > mobileUnitHandlerStart);
const mobileUnitHandler = html.slice(mobileUnitHandlerStart, mobileAmountHandlerStart);
assert.match(mobileUnitHandler, /stockUnitAmountFromBase\(baseStock,selected\?\.factor\|\|1\)/);
assert.match(mobileUnitHandler, /amountInput\.dataset\.factor=/);
assert.doesNotMatch(mobileUnitHandler, /render\(\)/);
assert.match(html, /<label>รหัสสินค้า<\/label>/);
assert.match(html, /<label>สินค้า<\/label>/);
assert.match(html, /<label>หน่วย<\/label>/);
assert.match(html, /<label>คงเหลือ<\/label>/);
assert.match(html, /stockEditImportInspectionList\(listId,true\)/);
assert.match(html, /mobileConfirmStockEdit'\)\?\.addEventListener\('click',confirmMobileStockEditChanges\)/);
assert.match(html, /function confirmMobileStockEditChanges\(/);
assert.match(html, /stockEditItems=\[\]/);
assert.match(html, /availableLists=lists\.filter\(inspectionListAvailableForStockEdit\)/);
assert.match(html, /แก้ไขจำนวนเรียบร้อย/);
assert.match(html, /<link rel="manifest" href="\/manifest\.webmanifest">/);
assert.match(html, /navigator\.serviceWorker\.register\('\/sw\.js'\)/);
assert.match(html, /beforeinstallprompt/);
assert.match(html, /id="mobileInstallApp"/);
assert.match(html, /intent:\/\/\$\{target\}#Intent;scheme=https;package=com\.android\.chrome/);
assert.match(html, /openMobileBrowserHelp\(\{cameraBlocked:true/);
assert.match(html, /if\(currentTab==='mobiletools'&&mobileToolMode==='price'\)/);
assert.doesNotMatch(html, /setTimeout\(\(\)=>document\.getElementById\('mobileInspectionInput'\)\?\.(?:focus|select)/);
assert.doesNotMatch(html, /setTimeout\(\(\)=>document\.getElementById\('mobileStockInput'\)\?\.(?:focus|select)/);

const mobilePriceResultStart = html.indexOf('function mobilePriceResultHtml(');
const mobilePriceResultEnd = html.indexOf('function mobileInspectionCurrentList(', mobilePriceResultStart);
assert.ok(mobilePriceResultStart >= 0 && mobilePriceResultEnd > mobilePriceResultStart);
const mobilePriceResult = html.slice(mobilePriceResultStart, mobilePriceResultEnd);
const mobilePriceNameIndex = mobilePriceResult.indexOf('mobile-result-name');
const mobilePriceUnitIndex = mobilePriceResult.indexOf('mobile-unit-select');
const mobilePriceStockIndex = mobilePriceResult.indexOf('<span>คงเหลือ</span>');
const mobilePriceSaleIndex = mobilePriceResult.indexOf('<span>ราคาขาย</span>');
const mobilePriceCostIndex = mobilePriceResult.indexOf('<span>ทุน</span>');
const mobilePriceExpiryIndex = mobilePriceResult.indexOf('<span>วันหมดอายุ</span>');
assert.ok(mobilePriceNameIndex >= 0 && mobilePriceUnitIndex > mobilePriceNameIndex && mobilePriceStockIndex > mobilePriceUnitIndex && mobilePriceSaleIndex > mobilePriceStockIndex && mobilePriceCostIndex > mobilePriceSaleIndex && mobilePriceExpiryIndex > mobilePriceCostIndex);
assert.match(mobilePriceResult, /mobile-metric primary[^>]*><span>คงเหลือ<\/span>/);
assert.doesNotMatch(mobilePriceResult, /mobile-result-codes/);
const mobilePriceUnitHandlerStart = html.indexOf("document.getElementById('mobilePriceUnit')?.addEventListener('change'");
const mobilePriceCameraHandlerStart = html.indexOf("document.getElementById('mobilePriceCamera')?.addEventListener", mobilePriceUnitHandlerStart);
assert.ok(mobilePriceUnitHandlerStart >= 0 && mobilePriceCameraHandlerStart > mobilePriceUnitHandlerStart);
const mobilePriceUnitHandler = html.slice(mobilePriceUnitHandlerStart, mobilePriceCameraHandlerStart);
assert.doesNotMatch(mobilePriceUnitHandler, /render\(\)/);
assert.match(mobilePriceUnitHandler, /mobilePriceStock/);
assert.match(mobilePriceUnitHandler, /mobilePriceSale/);
assert.match(mobilePriceUnitHandler, /mobilePriceCost/);

assert.equal(manifest.display, 'standalone');
assert.equal(manifest.start_url, '/');
assert.ok(manifest.icons.some(icon => icon.src === '/pwa-icon.svg'));
assert.ok(manifest.icons.some(icon => icon.src === '/pwa-icon-192.png' && icon.sizes === '192x192'));
assert.ok(manifest.icons.some(icon => icon.src === '/pwa-icon-512.png' && icon.sizes === '512x512'));
assert.match(serviceWorker, /request\.mode==='navigate'/);
assert.match(serviceWorker, /fetch\(request\)/);
assert.match(serviceWorker, /caches\.match\('\/index\.html'\)/);
assert.match(serviceWorker, /pepos-mobile-v4/);
assert.match(serviceWorker, /cdn\.jsdelivr\.net/);
assert.ok(fs.statSync(path.join(root, 'pwa-icon-192.png')).size > 1000);
assert.ok(fs.statSync(path.join(root, 'pwa-icon-512.png')).size > 3000);

const functionStart = html.indexOf('function mobileProductMatches(');
const functionEnd = html.indexOf('function mobilePriceMatches(', functionStart);
assert.ok(functionStart >= 0 && functionEnd > functionStart, 'ไม่พบฟังก์ชันค้นหาสินค้าสำหรับมือถือ');
const context = {
  matchesBarcode(product, query) {
    return product.barcode === query || (product.units || []).some(unit => unit.barcode === query);
  },
};
vm.createContext(context);
vm.runInContext(html.slice(functionStart, functionEnd), context);
const product = { name: 'Vitamin C 1000', sku: 'P-100', barcode: '885000100', units: [{ barcode: 'BOX-100' }] };
assert.equal(context.mobileProductMatches(product, 'vitamin'), true);
assert.equal(context.mobileProductMatches(product, 'P-100'), true);
assert.equal(context.mobileProductMatches(product, 'BOX-100'), true);
assert.equal(context.mobileProductMatches(product, 'ไม่มี'), false);
assert.equal(context.mobileProductMatches(product, ''), false);

console.log('mobile tools tests passed');
