const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.webmanifest'), 'utf8'));
const serviceWorker = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');

assert.match(html, /mobiletools:\s*renderMobileTools/);
assert.match(html, /if\(mobileMode\) currentTab='mobiletools'/);
assert.match(html, /body\.mobile-device-mode \.sidebar,body\.mobile-device-mode \.topbar\{display:none!important/);
assert.match(html, /data-mobile-tool="price"/);
assert.match(html, /data-mobile-tool="inventory"/);
assert.doesNotMatch(html, /data-mobile-tool="inspection"/);
assert.doesNotMatch(html, /data-mobile-tool="stock"/);
assert.match(html, /data-mobile-inventory-step="inspection"/);
assert.match(html, /data-mobile-inventory-step="stock"/);
assert.match(html, /ตรวจและแก้ไขสต๊อก/);
assert.match(html, /id="mobileContinueToStock"/);
assert.match(html, /id="mobileOpenInspectionList"/);
assert.match(html, /id="mobileDeleteInspectionList"/);
assert.match(html, /id="mobileDeleteInspectionList"[^>]*>ลบบันทึก<\/button>/);
assert.match(html, /deleteInspectionListById\(list\.id\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandlePriceCode,\{continuous:true,hostId:'mobilePriceCameraSlot',buttonId:'mobilePriceCamera'\}\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandleInspectionCode,\{continuous:true,hostId:'mobileInspectionCameraSlot',buttonId:'mobileInspectionCamera'\}\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandleStockCode,\{continuous:true,hostId:'mobileStockCameraSlot',buttonId:'mobileStockCamera'\}\)/);
assert.match(html, /const MOBILE_SCAN_SOUND_URL='data:audio\/mpeg;base64,/);
assert.doesNotMatch(html, /\/mobile-scan-success\.mp3/);
const embeddedScanSound=html.match(/const MOBILE_SCAN_SOUND_URL='data:audio\/mpeg;base64,([^']+)'/);
assert.ok(embeddedScanSound&&Buffer.from(embeddedScanSound[1],'base64').length>1000);
assert.equal(fs.existsSync(path.join(root,'mobile-scan-success.mp3')),false);
assert.match(html, /mobileScanSound=new Audio\(MOBILE_SCAN_SOUND_URL\)/);
assert.match(html, /sound\.currentTime=0/);
assert.ok((html.match(/playMobileScanSound\(\)/g)||[]).length >= 5);
assert.equal((html.match(/unlockMobileScanSound\(\); openMobileCameraScanner/g)||[]).length, 4);
assert.match(html, /const continuous=options\.continuous===true/);
assert.match(html, /if\(!continuous\)\{ closeMobileCameraScanner\(\); onCode\(value\); return; \}/);
assert.match(html, /ยิงได้หลายสินค้า กด × เมื่อต้องการปิด/);
assert.match(html, /value!==lastValue/);
assert.match(html, /class="mobile-camera-slot" id="mobilePriceCameraSlot"/);
assert.equal((html.match(/class="mobile-camera-slot" id="mobileInspectionCameraSlot"/g)||[]).length, 1);
assert.match(html, /class="mobile-camera-slot" id="mobileStockCameraSlot"/);
assert.match(html, /camera\.className='mobile-camera-inline'/);
assert.doesNotMatch(html, /mobile-camera-overlay/);
assert.doesNotMatch(html, /\.mobile-camera-inline\{[^}]*position:fixed/);
assert.match(html, /function preserveMobileCameraScanner\(\)/);
assert.match(html, /function restoreMobileCameraScanner\(\)/);
assert.match(html, /findProductByExactCode\(query\)/);
assert.match(html, /mobileInspectionCheckedSet\(list\.id\)\.add/);
assert.match(html, /id="mobileNewInspectionList"/);
assert.match(html, /function startMobileInspectionDraft\(/);
assert.match(html, /const defaultName=inspectionListDefaultName\(\)/);
assert.match(html, /return `ตรวจสินค้า: \$\{highest\+1\}`/);
assert.match(html, /function addProductToMobileInspectionDraft\(/);
assert.match(html, /inspectionListAddProduct\(product,unitName\)/);
assert.match(html, /id="mobileSaveInspectionDraft"/);
assert.match(html, /data-mobile-draft-add=/);
assert.match(html, /data-mobile-draft-remove=/);
assert.match(html, /data-mobile-inspection-remove=/);
assert.match(html, /function removeProductFromMobileInspection\(/);
assert.match(html, /event\.stopPropagation\(\)/);
assert.match(html, /function saveMobileInspectionDraft\(/);
assert.match(html, /saveInspectionListDraft\(\{sync:false\}\)/);
assert.match(html, /id="mobileInspectionAddToggle"/);
assert.match(html, /id="mobileInspectionAddInput"/);
assert.match(html, /id="mobileInspectionAddCamera"/);
assert.match(html, /id="mobileInspectionAddSave"/);
assert.match(html, /data-mobile-inspection-add-result=/);
assert.match(html, /data-mobile-inspection-add-remove=/);
assert.match(html, /function addProductToMobileInspectionSavedDraft\(/);
assert.match(html, /async function saveMobileInspectionSavedAdd\(/);
assert.match(html, /บันทึกสินค้าที่เพิ่ม \(\$\{count\}\)/);
assert.match(html, /openMobileCameraScanner\(mobileHandleInspectionCode,\{continuous:true,hostId:'mobileInspectionAddCameraSlot',buttonId:'mobileInspectionAddCamera'\}\)/);
assert.match(html, /function mobileInspectionVisibleLists\(\)/);
assert.match(html, /return inspectionLists\.filter\(list=>!String\(list\?\.stockAdjustedAt\|\|''\)\.trim\(\)\)/);
assert.match(html, /const lists=\[\.\.\.mobileInspectionVisibleLists\(\)\]/);
assert.match(html, /function renderMobileStockEditPanel\(/);
assert.match(html, /id="mobileStockSourceList"/);
assert.match(html, /id="mobileStockImport"/);
assert.match(html, /id="mobileStockInput"/);
assert.match(html, /id="mobileConfirmStockEdit"/);
const mobileStockPanelStart = html.indexOf('function renderMobileStockEditPanel(');
const mobileStockPanelEnd = html.indexOf('async function confirmMobileStockEditChanges(', mobileStockPanelStart);
const mobileStockPanel = html.slice(mobileStockPanelStart, mobileStockPanelEnd);
assert.doesNotMatch(mobileStockPanel, /<h2 class="mobile-tool-title">แก้ไขสต๊อก<\/h2>/);
assert.doesNotMatch(mobileStockPanel, /ดึงรายการตรวจสินค้า หรือยิงบาร์โค้ด แล้วกรอกจำนวนใหม่ก่อนยืนยันพร้อมกัน/);
assert.doesNotMatch(mobileStockPanel, /แก้ตัวเลขแล้วสต๊อกจะยังไม่เปลี่ยน/);
assert.match(mobileStockPanel, /\$\{mobileStockEditRowsHtml\(\)\}\$\{reasonHtml\}<div class="mobile-stock-confirm-wrap">/);
assert.match(html, /id="mobileToolsRefresh"/);
assert.match(html, /refreshMobileToolsData\(mobileToolsRefresh\)/);
assert.match(html, /id="mobileDataStatus"/);
assert.match(html, /คลัง: \$\{warehouseName\}/);
assert.match(html, /window\.addEventListener\('online'/);
assert.match(html, /window\.addEventListener\('offline'/);
assert.match(html, /document\.addEventListener\('visibilitychange'/);
assert.match(html, /refreshMobileToolsOnResume/);
assert.match(html, /mobileRequireOnline\('ยืนยันแก้ไขสต๊อก'\)/);
assert.match(html, /if\(confirm\('ยืนยันการออกจากระบบใช่หรือไม่\?'\)\)\{ closeMobileCameraScanner\(\); logoutSystem\(\); \}/);
assert.match(html, /body\.mobile-device-mode \.mobile-tools-head\{position:fixed;left:0;right:0;bottom:0;/);
assert.match(html, /body\.mobile-device-mode \.mobile-tools-page\{[^}]*padding:[^;]*calc\(86px \+ env\(safe-area-inset-bottom\)\)/);
assert.match(html, /body\.mobile-device-mode \.mobile-draft-save-wrap,body\.mobile-device-mode \.mobile-stock-confirm-wrap\{bottom:calc\(62px \+ env\(safe-area-inset-bottom\)\)/);
assert.match(html, /\.mobile-tools-brand>div:first-child\{[^}]*text-align:right;/);
const mobileToolsRenderStart = html.indexOf('function renderMobileTools()');
const mobileToolsRenderEnd = html.indexOf('function mobileHandlePriceCode(', mobileToolsRenderStart);
const mobileToolsRender = html.slice(mobileToolsRenderStart, mobileToolsRenderEnd);
assert.ok(mobileToolsRender.indexOf('mobile-tools-head') > mobileToolsRender.indexOf('mobile-tool-panel'));
const mobileFooterStart = mobileToolsRender.indexOf('<header class="mobile-tools-head">');
const mobileFooterEnd = mobileToolsRender.indexOf('</header>', mobileFooterStart);
const mobileFooter = mobileToolsRender.slice(mobileFooterStart, mobileFooterEnd);
const mobileLogoutIndex = mobileFooter.indexOf('id="mobileToolsLogout"');
const mobileRefreshIndex = mobileFooter.indexOf('id="mobileToolsRefresh"');
const mobileTitleIndex = mobileFooter.indexOf('<h1>PEPOS</h1>');
const mobileLogoIndex = mobileFooter.indexOf('mobile-tools-logo">Rx');
assert.ok(mobileLogoutIndex >= 0 && mobileRefreshIndex > mobileLogoutIndex && mobileTitleIndex > mobileRefreshIndex && mobileLogoIndex > mobileTitleIndex);
const mainRenderStart = html.indexOf('function render(){');
const mainRenderEnd = html.indexOf('function syncTopbarFormActions()', mainRenderStart);
const mainRender = html.slice(mainRenderStart, mainRenderEnd);
const preserveCameraIndex = mainRender.indexOf('preserveMobileCameraScanner();');
const replaceMainIndex = mainRender.indexOf('mainElement.innerHTML');
const restoreCameraIndex = mainRender.indexOf('restoreMobileCameraScanner();');
assert.ok(preserveCameraIndex >= 0 && preserveCameraIndex < replaceMainIndex && replaceMainIndex < restoreCameraIndex, 'ต้องรักษากรอบกล้องไว้ระหว่าง render');
assert.match(html, /await Promise\.all\(\[loadCoreDataFromSupabase\(\),loadInspectionListsFromSupabase\(\)\]\)/);
assert.match(html, /data-mobile-stock-amount=/);
assert.match(html, /data-mobile-stock-unit=/);
assert.match(html, /class="mobile-stock-info-row"/);
assert.match(html, /class="mobile-stock-edit-row"/);
assert.match(html, /data-mobile-stock-remove=/);
assert.match(html, /\.mobile-stock-edit-row\{[^}]*grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\) 42px/);
const mobileStockRemoveHandlerStart = html.indexOf("document.querySelectorAll('[data-mobile-stock-remove]')");
const mobileStockUnitHandlerStart = html.indexOf("document.querySelectorAll('[data-mobile-stock-unit]')", mobileStockRemoveHandlerStart);
assert.ok(mobileStockRemoveHandlerStart >= 0 && mobileStockUnitHandlerStart > mobileStockRemoveHandlerStart);
const mobileStockRemoveHandler = html.slice(mobileStockRemoveHandlerStart, mobileStockUnitHandlerStart);
assert.match(mobileStockRemoveHandler, /stockEditItems=stockEditItems\.filter/);
assert.match(mobileStockRemoveHandler, /delete stockEditRowUnitSel\[productId\]/);
assert.match(mobileStockRemoveHandler, /delete stockEditDraftStocks\[productId\]/);
const mobileUnitHandlerStart = html.indexOf("document.querySelectorAll('[data-mobile-stock-unit]')");
const mobileAmountHandlerStart = html.indexOf("document.querySelectorAll('[data-mobile-stock-amount]')", mobileUnitHandlerStart);
assert.ok(mobileUnitHandlerStart >= 0 && mobileAmountHandlerStart > mobileUnitHandlerStart);
const mobileUnitHandler = html.slice(mobileUnitHandlerStart, mobileAmountHandlerStart);
assert.match(mobileUnitHandler, /stockUnitAmountFromBase\(baseStock,selected\?\.factor\|\|1\)/);
assert.match(mobileUnitHandler, /amountInput\.dataset\.factor=/);
assert.doesNotMatch(mobileUnitHandler, /render\(\)/);
assert.match(html, /<label>รหัสสินค้า<\/label>/);
assert.match(html, /<label>สินค้า<\/label>/);
assert.match(html, /<label>หน่วย<\/label>/);
assert.match(html, /<label>คงเหลือ<\/label>/);
assert.match(html, /stockEditImportInspectionList\(listId,true\)/);
assert.match(html, /mobileInventoryStep='stock'/);
assert.match(html, /mobileStockSourceListId=list\.id/);
assert.match(html, /mobileConfirmStockEdit'\)\?\.addEventListener\('click',confirmMobileStockEditChanges\)/);
assert.match(html, /function confirmMobileStockEditChanges\(/);
assert.match(html, /stockEditItems=\[\]/);
assert.match(html, /availableLists=lists\.filter\(inspectionListAvailableForStockEdit\)/);
assert.match(html, /แก้ไขจำนวนเรียบร้อย/);
assert.match(html, /<link rel="manifest" href="\/manifest\.webmanifest">/);
assert.match(html, /navigator\.serviceWorker\.register\('\/sw\.js'\)/);
assert.match(html, /beforeinstallprompt/);
assert.match(html, /id="mobileInstallApp"/);
assert.match(html, /intent:\/\/\$\{target\}#Intent;scheme=https;package=com\.android\.chrome/);
assert.match(html, /openMobileBrowserHelp\(\{cameraBlocked:true/);
assert.match(html, /if\(currentTab==='mobiletools'&&mobileToolMode==='price'&&!mobileCameraSession\)/);
assert.match(html, /if\(!mobileCameraSession\) setTimeout\(\(\)=>document\.getElementById\('mobilePriceInput'\)\?\.select\(\),0\)/);
assert.doesNotMatch(html, /setTimeout\(\(\)=>document\.getElementById\('mobileInspectionInput'\)\?\.(?:focus|select)/);
assert.doesNotMatch(html, /setTimeout\(\(\)=>document\.getElementById\('mobileStockInput'\)\?\.(?:focus|select)/);

const mobilePriceResultStart = html.indexOf('function mobilePriceResultHtml(');
const mobilePriceResultEnd = html.indexOf('function mobileInspectionCurrentList(', mobilePriceResultStart);
assert.ok(mobilePriceResultStart >= 0 && mobilePriceResultEnd > mobilePriceResultStart);
const mobilePriceResult = html.slice(mobilePriceResultStart, mobilePriceResultEnd);
const mobilePriceNameIndex = mobilePriceResult.indexOf('mobile-result-name');
const mobilePriceUnitIndex = mobilePriceResult.indexOf('mobile-unit-select');
const mobilePriceStockIndex = mobilePriceResult.indexOf('<span>คงเหลือ</span>');
const mobilePriceSaleIndex = mobilePriceResult.indexOf('<span>ราคาขาย</span>');
const mobilePriceCostIndex = mobilePriceResult.indexOf('<span>ทุน</span>');
const mobilePriceExpiryIndex = mobilePriceResult.indexOf('<span>วันหมดอายุ</span>');
assert.ok(mobilePriceNameIndex >= 0 && mobilePriceUnitIndex > mobilePriceNameIndex && mobilePriceStockIndex > mobilePriceUnitIndex && mobilePriceSaleIndex > mobilePriceStockIndex && mobilePriceCostIndex > mobilePriceSaleIndex && mobilePriceExpiryIndex > mobilePriceCostIndex);
assert.match(mobilePriceResult, /mobile-metric primary[^>]*><span>คงเหลือ<\/span>/);
assert.doesNotMatch(mobilePriceResult, /mobile-result-codes/);
assert.match(html, /\.mobile-result-card\{[^}]*text-align:center;/);
assert.match(html, /\.mobile-unit-select\{[^}]*text-align:center;[^}]*text-align-last:center;/);
assert.match(html, /data-mobile-tool="inventory">ตรวจและแก้ไขสต๊อก<\/button>/);
assert.doesNotMatch(html, /<h2 class="mobile-tool-title">ตรวจสินค้า<\/h2>/);
assert.doesNotMatch(html, /สร้างรายการใหม่ หรือเปิดรายการที่บันทึกไว้เพื่อสแกนตรวจสินค้า/);
assert.doesNotMatch(html, /ยิงแล้วสินค้าจะเพิ่มเข้ารายการทันที หรือพิมพ์ชื่อแล้วแตะสินค้าที่ต้องการ/);
const savedInspectionPanelStart = html.indexOf('function renderMobileInspectionPanel(');
const savedInspectionPanelEnd = html.indexOf('function addProductToMobileInspectionDraft(', savedInspectionPanelStart);
assert.ok(savedInspectionPanelStart >= 0 && savedInspectionPanelEnd > savedInspectionPanelStart);
const savedInspectionPanel = html.slice(savedInspectionPanelStart, savedInspectionPanelEnd);
assert.doesNotMatch(savedInspectionPanel, /id="mobileInspectionInput"/);
assert.doesNotMatch(savedInspectionPanel, /id="mobileInspectionCamera"/);
const mobilePriceUnitHandlerStart = html.indexOf("document.getElementById('mobilePriceUnit')?.addEventListener('change'");
const mobilePriceUnitHandlerEnd = html.indexOf("\n  });", mobilePriceUnitHandlerStart);
assert.ok(mobilePriceUnitHandlerStart >= 0 && mobilePriceUnitHandlerEnd > mobilePriceUnitHandlerStart);
const mobilePriceUnitHandler = html.slice(mobilePriceUnitHandlerStart, mobilePriceUnitHandlerEnd);
assert.doesNotMatch(mobilePriceUnitHandler, /render\(\)/);
assert.match(mobilePriceUnitHandler, /mobilePriceStock/);
assert.match(mobilePriceUnitHandler, /mobilePriceSale/);
assert.match(mobilePriceUnitHandler, /mobilePriceCost/);
const mobilePriceInputHandlerStart = html.indexOf("mobilePriceInput.addEventListener('input'");
const mobilePriceInputHandlerEnd = html.indexOf("mobilePriceInput.addEventListener('keydown'", mobilePriceInputHandlerStart);
assert.ok(mobilePriceInputHandlerStart >= 0 && mobilePriceInputHandlerEnd > mobilePriceInputHandlerStart);
const mobilePriceInputHandler = html.slice(mobilePriceInputHandlerStart, mobilePriceInputHandlerEnd);
assert.doesNotMatch(mobilePriceInputHandler, /render\(\)/);
assert.match(mobilePriceInputHandler, /result\.innerHTML=mobilePriceResultHtml\(\)/);
assert.match(mobilePriceInputHandler, /attachMobilePriceResultEvents\(\)/);

assert.equal(manifest.display, 'standalone');
assert.equal(manifest.short_name, 'PEPOS');
assert.equal(manifest.start_url, '/');
assert.ok(manifest.icons.some(icon => icon.src === '/pwa-icon.svg'));
assert.ok(manifest.icons.some(icon => icon.src === '/pwa-icon-192.png' && icon.sizes === '192x192'));
assert.ok(manifest.icons.some(icon => icon.src === '/pwa-icon-512.png' && icon.sizes === '512x512'));
assert.match(serviceWorker, /request\.mode==='navigate'/);
assert.match(serviceWorker, /fetch\(request\)/);
assert.match(serviceWorker, /caches\.match\('\/index\.html'\)/);
assert.match(serviceWorker, /pepos-mobile-v7/);
assert.doesNotMatch(serviceWorker, /\/mobile-scan-success\.mp3/);
assert.match(serviceWorker, /cdn\.jsdelivr\.net/);
assert.ok(fs.statSync(path.join(root, 'pwa-icon-192.png')).size > 1000);
assert.ok(fs.statSync(path.join(root, 'pwa-icon-512.png')).size > 3000);

const soundFunctionStart = html.indexOf('function prepareMobileScanSound(');
const soundFunctionEnd = html.indexOf('function mobileHandleStockCode(', soundFunctionStart);
assert.ok(soundFunctionStart >= 0 && soundFunctionEnd > soundFunctionStart, 'ไม่พบฟังก์ชันเสียงสแกนบาร์โค้ด');
const sounds = [];
class FakeAudio {
  constructor(src) {
    this.src = src;
    this.preload = '';
    this.muted = false;
    this.currentTime = 4;
    this.loadCount = 0;
    this.pauseCount = 0;
    this.playCount = 0;
    sounds.push(this);
  }
  load() { this.loadCount += 1; }
  pause() { this.pauseCount += 1; }
  play() { this.playCount += 1; return Promise.resolve(); }
}
const soundContext = { Audio: FakeAudio, console };
vm.createContext(soundContext);
vm.runInContext(`const MOBILE_SCAN_SOUND_URL='data:audio/mpeg;base64,SUQz'; let mobileScanSound=null; ${html.slice(soundFunctionStart, soundFunctionEnd)}`, soundContext);
assert.equal(soundContext.playMobileScanSound(), true);
assert.equal(soundContext.playMobileScanSound(), true);
assert.equal(sounds.length, 1);
assert.equal(sounds[0].src, 'data:audio/mpeg;base64,SUQz');
assert.equal(sounds[0].preload, 'auto');
assert.equal(sounds[0].loadCount, 1);
assert.equal(sounds[0].pauseCount, 2);
assert.equal(sounds[0].playCount, 2);
assert.equal(sounds[0].currentTime, 0);

const functionStart = html.indexOf('function mobileProductMatches(');
const functionEnd = html.indexOf('function mobilePriceMatches(', functionStart);
assert.ok(functionStart >= 0 && functionEnd > functionStart, 'ไม่พบฟังก์ชันค้นหาสินค้าสำหรับมือถือ');
const context = {
  matchesBarcode(product, query) {
    return product.barcode === query || (product.units || []).some(unit => unit.barcode === query);
  },
};
vm.createContext(context);
vm.runInContext(html.slice(functionStart, functionEnd), context);
const product = { name: 'Vitamin C 1000', sku: 'P-100', barcode: '885000100', units: [{ barcode: 'BOX-100' }] };
assert.equal(context.mobileProductMatches(product, 'vitamin'), true);
assert.equal(context.mobileProductMatches(product, 'P-100'), true);
assert.equal(context.mobileProductMatches(product, 'BOX-100'), true);
assert.equal(context.mobileProductMatches(product, 'ไม่มี'), false);
assert.equal(context.mobileProductMatches(product, ''), false);

console.log('mobile tools tests passed');
