const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');
const ctx=vm.createContext({products:[],barcodePrintBarcodeOwners:()=>[],extraBarcodeEntries:p=>(p.extraBarcodes||[]).map((code,i)=>({code,unit:p.extraBarcodeUnits?.[i]||p.unit}))});
const start=source.indexOf('function mobileProductValidationError(');
vm.runInContext(source.slice(start,source.indexOf('function attachMobileProductEditorEvents(',start)),ctx);
const product={name:'A',sku:'A-1',unit:'กล่อง',price:100,cost:50,barcode:'BASE',units:[{sub:'ลัง',per:10,factor:10,price:950,cost:450,barcode:'CASE'}]};
assert.equal(ctx.mobileProductValidationError(product,null),'');
for(const price of [-1,Infinity,NaN])assert.ok(ctx.mobileProductValidationError({...product,price},null));
assert.ok(ctx.mobileProductValidationError({...product,cost:-1},null));
for(const factor of [0,-1,Infinity,NaN])assert.ok(ctx.mobileProductValidationError({...product,units:[{...product.units[0],factor}]},null));
assert.ok(ctx.mobileProductValidationError({...product,units:[{...product.units[0],sub:'กล่อง'}]},null));
assert.ok(ctx.mobileProductValidationError({...product,units:[product.units[0],product.units[0]]},null));
assert.ok(ctx.mobileProductValidationError({...product,units:[{...product.units[0],barcode:'BASE'}]},null));
const existing={id:1,unit:'กล่อง',extraBarcodes:['LEGACY'],extraBarcodeUnits:['ลัง']};
assert.equal(ctx.mobileProductValidationError(product,existing),'');
assert.ok(ctx.mobileProductValidationError({...product,units:[]},existing),'do not orphan hidden extra barcodes');
ctx.barcodePrintBarcodeOwners=()=>[{pid:2,code:'case'}];
assert.ok(ctx.mobileProductValidationError(product,null),'case-insensitive barcode collision with another product');
ctx.barcodePrintBarcodeOwners=()=>[{pid:1,code:'case'}];
assert.equal(ctx.mobileProductValidationError(product,existing),'','existing product keeps its own barcode');
ctx.products=[{id:2,sku:'a-1'}];
assert.ok(ctx.mobileProductValidationError(product,existing),'duplicate SKU rejected');
assert.match(source,/mobileEditor\?extraBarcodeEntries\(mobileEditor\.draft\)/);
assert.match(source,/mobileProductEditor\|\|mobileProductOpening\) return false/);
assert.match(source,/if\(!canEditMobilePrice\(\)\|\|mobileProductOpening\|\|mobileProductEditor\) return/);
console.log('mobile product editor validation tests passed');
