const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = require("./load-app-source")();
const start = html.indexOf('function renderProducts()');
const end = html.indexOf('function comboSelectorFor(', start);
assert.ok(start >= 0 && end > start, 'ไม่พบฟังก์ชัน renderProducts');

const source = html.slice(start, end);
const pageIndex = source.indexOf('<div class="product-list-page">');
const actionsIndex = source.indexOf('<div class="product-list-actions form-final-actions">');
const groupIndex = source.indexOf('<div class="tree-pane">');
const searchIndex = source.indexOf('<div class="searchbar product-list-search"><input id="search"');
const tableIndex = source.indexOf('<div class="table-pane">');

assert.ok(actionsIndex >= 0, 'ไม่พบกลุ่มปุ่มสำหรับย้ายขึ้น topbar');
assert.ok(groupIndex > actionsIndex, 'กลุ่มปุ่มต้องอยู่ก่อนเนื้อหาหน้าสินค้าเพื่อให้ระบบย้ายขึ้น topbar');
assert.ok(groupIndex >= 0, 'ไม่พบกล่องกลุ่มสินค้า');
assert.ok(searchIndex > groupIndex, 'ช่องค้นหาต้องอยู่หลังกล่องกลุ่มสินค้า');
assert.ok(tableIndex > searchIndex, 'ช่องค้นหาต้องอยู่ก่อนตารางข้อมูลสินค้า');
assert.match(source, /product-group-header[^>]*><span class="product-group-title">กลุ่มสินค้า<\/span><span class="product-group-separator">:<\/span><div class="product-group-categories">/, 'ชื่อและหมวดหลักต้องอยู่แถวเดียวกันในแถบสีฟ้า');
assert.match(source, /<div class="product-group-brands">\$\{brandHtml\}<\/div>/, 'หมวดย่อยต้องแสดงในพื้นที่สีขาวใต้แถบหมวดหลัก');
assert.match(source, /requestedCategoryOrder=\['ยา','อาหารเสริม','อื่นๆ','ไม่ทราบหมวดหมู่'\]/, 'หมวดหลักต้องเรียงตามลำดับที่กำหนด');
assert.match(source, /class="product-group-category \$\{active\?'active':''\}" data-product-category=/, 'หมวดหลักต้องกดเลือกได้');
assert.match(source, /class="product-group-brand \$\{active\?'active':''\}" data-product-category=.*data-product-brand=/, 'หมวดย่อยต้องกดเลือกได้');
assert.doesNotMatch(source, /tree-cat-row|tree-brand-flyout/, 'หน้ารายการสินค้าต้องไม่ใช้โครงสร้างหมวดหลักแนวตั้งเดิม');
assert.match(html, /\.product-list-search\{[^}]*max-width:none;[^}]*width:100%/);
assert.match(html, /\.product-list-actions\{[^}]*display:flex/);
assert.match(html, /\.product-group-category\{[^}]*background:#fff;[^}]*color:#76574C;/, 'หมวดสินค้าหลักทุกปุ่มต้องเป็นพื้นขาวและตัวอักษรน้ำตาล');
assert.match(html, /\.product-group-category-count\{[^}]*background:#F3EBE8;[^}]*color:#76574C;/, 'จำนวนสินค้าในหมวดต้องใช้ป้ายสีน้ำตาลอ่อน');
assert.match(html, /\.product-group-category\.active\{[^}]*border-color:#C6AAA0;/, 'หมวดที่เลือกต้องยังมีสถานะแยกให้สังเกตได้');
assert.doesNotMatch(source, /product-head-search/);
assert.doesNotMatch(source, /pagehead product-pagehead/);
assert.match(source, /<col class="col-sku"><col class="col-barcode"><col class="col-name">/, 'คอลัมน์บาร์โค้ดต้องอยู่ถัดจากรหัสสินค้า');
assert.match(source, /\$\{th\('sku','รหัสสินค้า'\)\}<th>บาร์โค้ด<\/th>\$\{th\('name','สินค้า'\)\}/, 'หัวข้อบาร์โค้ดต้องอยู่ระหว่างรหัสสินค้าและชื่อสินค้า');
assert.match(source, /barcode:p\.barcode\|\|''[^]*barcode:u\.barcode\|\|''/, 'รายการหน่วยต้องเก็บบาร์โค้ดของทั้งหน่วยหลักและหน่วยเพิ่มเติม');
assert.match(source, /class="prod-inline-edit prod-inline-barcode prod-unit-barcode"[^]*data-field="barcode"[^]*data-unit="\$\{escapeHtml\(selOpt\.sub\)\}"[^]*value="\$\{escapeHtml\(selOpt\.barcode\|\|''\)\}"/, 'แถวสินค้าต้องแก้บาร์โค้ดของหน่วยที่เลือกได้');
assert.match(html, /field==='barcode'[^]*barcodePrintBarcodeOwners\(\)\.find[^]*unitRow\.barcode=requested;[^]*p\.barcode=requested;/, 'การแก้บาร์โค้ดต้องตรวจเลขซ้ำและบันทึกลงหน่วยที่เลือก');
assert.match(html, /\.prodtable \.col-barcode\{width:170px;\}/, 'คอลัมน์บาร์โค้ดต้องมีความกว้างอ่านเลขได้ชัดเจน');
assert.match(source, /data-toggle-product-reviewed="\$\{p\.id\}"[^]*aria-pressed="\$\{dataReviewed\?'true':'false'\}"/, 'ท้ายแถวสินค้าต้องมีปุ่มติ๊กเพื่อระบุว่าตรวจข้อมูลครบแล้ว');
assert.match(html, /document\.querySelectorAll\('\[data-toggle-product-reviewed\]'\)[^]*product\.dataReviewedAt=new Date\(\)\.toISOString\(\);[^]*persistWorkspaceData\(\{productChanges:\{updatedIds:\[pid\]\}\}\)/, 'สถานะตรวจข้อมูลต้องบันทึกลงข้อมูลสินค้าและซิงก์ได้');
assert.match(html, /\.product-reviewed-row>td\{background:#EFF9F1;color:#237A3A;\}/, 'แถวที่ตรวจข้อมูลครบแล้วต้องแสดงพื้นและตัวอักษรสีเขียว');
assert.match(source, /placeholder="ค้นหาจาก ชื่อ \/ รหัส \/ บาร์โค้ด"/, 'ยังต้องค้นหาด้วยบาร์โค้ดได้');
assert.match(html, /function restoreSearchInputFocus\(selectionStart,selectionEnd\)/, 'ต้องมีตัวช่วยคืนโฟกัสและตำแหน่งเคอร์เซอร์ให้ช่องค้นหา');
assert.match(html, /if\(e\.isComposing\) return;[^]*restoreSearchInputFocus\(selectionStart,selectionEnd\);/, 'ช่องค้นหาต้องไม่วาดหน้าใหม่ระหว่างประกอบอักษร และต้องคืนโฟกัสหลังกรองข้อมูล');
assert.match(html, /listSearchRenderTimer=setTimeout\(\(\)=>\{[^]*\},120\);/, 'การกรองรายการต้องรอให้ผู้ใช้หยุดพิมพ์ช่วงสั้น ๆ เพื่อไม่ให้ตัวอักษรหาย');
assert.match(html, /if\(currentTab!==['"]products['"]\|\|e\.isComposing\) return;/, 'การตรวจจับเครื่องยิงต้องทำงานเฉพาะหน้ารายการสินค้า');
assert.match(html, /const productSearchStartingValue=String\(searchEl\.value\|\|''\)\.trim\(\)/, 'ต้องจำข้อความเดิมก่อนรับค่าจากเครื่องยิง');
assert.match(html, /const knownSuffix=\[\.\.\.exactProductCodeMap\.keys\(\)\][^]*currentValue\.endsWith/, 'ต้องตรวจบาร์โค้ดที่รู้จักจากท้ายข้อความโดยไม่ผูกกับความเร็วเครื่องยิง');
assert.match(html, /currentValue\.slice\(productSearchStartingValue\.length\)\.trim\(\)/, 'ต้องแยกค่าที่เครื่องยิงต่อท้ายข้อความค้นหาเดิม');
assert.match(html, /function selectProductListUnitByExactCode\(code\)[^]*prodRowUnitSel\[match\.product\.id\]=match\.unitName;/, 'ต้องจำหน่วยของบาร์โค้ดที่ค้นหาให้แถวสินค้า');
assert.match(html, /searchQuery=scannerValue;[^]*selectProductListUnitByExactCode\(scannerValue\);[^]*searchEl\.value=scannerValue;/, 'การยิงบาร์โค้ดต้องเลือกหน่วยที่ผูกกับบาร์โค้ดนั้น');
assert.match(html, /if\(searchTab===['"]products['"]\) selectProductListUnitByExactCode\(searchQuery\);/, 'การพิมพ์บาร์โค้ดตรงเองต้องเลือกหน่วยได้เช่นกัน');
assert.match(html, /searchQuery=scannerValue;[^]*searchEl\.value=scannerValue;[^]*nextSearch\.select\(\);/, 'บาร์โค้ดใหม่ต้องแทนข้อความค้นหาเดิมและพร้อมรับการยิงครั้งถัดไป');

const renderStart = html.indexOf('function render(){');
const renderEnd = html.indexOf('function syncTopbarFormActions()', renderStart);
const renderSource = html.slice(renderStart, renderEnd);
const clearTopbarIndex = renderSource.indexOf("topbarFormActionsSlot.innerHTML=''");
const mainClassIndex = renderSource.indexOf("mainElement.classList.toggle('product-list-main'");
const renderMainIndex = renderSource.indexOf('mainElement.innerHTML');
const attachEventsIndex = renderSource.indexOf('attachEvents();');
const syncTopbarIndex = renderSource.indexOf('syncTopbarFormActions();');
assert.ok(clearTopbarIndex >= 0 && clearTopbarIndex < renderMainIndex, 'ต้องล้างปุ่มเก่าใน topbar ก่อนสร้าง DOM หน้าใหม่');
assert.ok(mainClassIndex >= 0 && mainClassIndex < renderMainIndex, 'ต้องล็อกแถบเลื่อนด้านนอกเฉพาะหน้ารายการสินค้าก่อน render');
assert.ok(renderMainIndex < attachEventsIndex && attachEventsIndex < syncTopbarIndex, 'ต้องผูก event ก่อนย้ายปุ่มจริงขึ้น topbar');
assert.match(html, /main\.querySelectorAll\('\.form-final-actions'\)/);
assert.match(html, /\.main\.product-list-main\{overflow-y:hidden;\}/);
assert.match(html, /\.product-list-page\{height:100%;min-height:0;\}/);
assert.match(html, /\.product-list-page \.table-pane\{[^}]*flex:1;[^}]*min-height:0;[^}]*display:flex/);
assert.match(html, /\.product-list-page \.product-table-scroll\{[^}]*height:auto;[^}]*min-height:0;[^}]*flex:1/);
assert.match(html, /\.product-list-page \.pager\{[^}]*flex:0 0 auto/);

console.log('product layout tests passed');
assert.ok(pageIndex >= 0 && pageIndex < actionsIndex, 'หน้ารายการสินค้าต้องมีกรอบควบคุมความสูงเฉพาะหน้า');
