const assert=require('node:assert/strict');
const vm=require('node:vm');
const source=require('./load-app-source')();
const start=source.indexOf("const RECEIPT_PRINTER_STORAGE_KEY=");
const end=source.indexOf('function renderSystemSettings(',start);
assert.ok(start>=0&&end>start);
const entries=new Map();
const context={localStorage:{getItem:key=>entries.get(key)||null}};
vm.createContext(context);
vm.runInContext(source.slice(start,end),context);
const plain=value=>JSON.parse(JSON.stringify(value));
const defaults={paperWidth:80,marginTop:24,marginBottom:15,marginLeft:8,marginRight:8};
assert.deepEqual(plain(context.readReceiptPrinterSettings()),defaults,'preserve the original 80 mm layout by default');
entries.set('pepos_receipt_printer_v1','broken JSON');
assert.deepEqual(plain(context.readReceiptPrinterSettings()),defaults);
for(const value of [null,[],123,'text',{}]) assert.deepEqual(plain(context.normalizeReceiptPrinterSettings(value)),defaults);
assert.deepEqual(plain(context.normalizeReceiptPrinterSettings({paperWidth:'58',marginTop:Infinity,marginBottom:-9,marginLeft:100,marginRight:'2.55'})),{paperWidth:58,marginTop:24,marginBottom:0,marginLeft:10,marginRight:2.6});
entries.set('pepos_receipt_printer_v1',JSON.stringify({paperWidth:58,marginTop:2,marginBottom:3,marginLeft:4,marginRight:5}));
assert.equal(context.readReceiptPrinterSettings().paperWidth,58);
const css=context.receiptPrinterLayoutCss();
assert.match(css,/width:58mm;padding:2mm 5mm 3mm 4mm/);
assert.match(css,/@media print[\s\S]*width:58mm/,'print and screen sizes agree');
assert.match(css,/grid-template-columns:minmax\(0,1fr\) 16mm/);
assert.doesNotMatch(context.receiptPrinterLayoutCss({marginLeft:'1;display:none'}),/display:none(?!\!important)/,'storage values cannot inject CSS');
const sample=context.receiptPrinterTestHtml({paperWidth:58});
assert.match(sample,/TEST-0001/);
assert.match(sample,/ไม่บันทึกยอดขายและไม่ตัดสต๊อก/);
assert.doesNotMatch(sample,/<button|<script|https:\/\//,'embedded preview has no scripts, remote requests or print buttons');
const testCode=source.slice(source.indexOf('function printReceiptPrinterTest('),source.indexOf('function renderReceiptPrinterSettings('));
assert.match(testCode,/standardizePrintPreview\(win,\{trackPrint:false\}\)/,'test printing must not write a print event');
assert.doesNotMatch(testCode,/salesHistory|updateSale|sb\.|persistWorkspace|localStorage\.setItem/);
assert.match(source,/settingsusers[^\n]*\n\s*\['settingsprinter'/,'printer settings immediately follows user settings');
assert.match(source,/settingsprinter: \(\)=>renderReceiptPrinterSettings\(\)/);
const receipt=source.slice(source.indexOf('function printShortReceipt('),source.indexOf('async function doCheckout('));
assert.match(receipt,/applyReceiptPrinterLayout\(win\)/,'new and historical short receipts use this device layout');
console.log('receipt printer settings tests passed');
