const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const html = require('./load-app-source')();
const baseMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260904082715_representative_product_activity_notes.sql'), 'utf8');
const multiProductMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260904110037_representative_activity_multiple_products.sql'), 'utf8');
const managedProductsMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260904114305_representative_managed_products_and_notes.sql'), 'utf8');
const separatedEditorsMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260904142648_separate_representative_products_and_notes.sql'), 'utf8');
const historyRender = html.slice(html.indexOf('function renderRepresentativeHistory(){'),html.indexOf('function syncRepresentativeActivityDraftFromForm(){'));
const historyGroupRender = html.slice(html.indexOf('function representativeHistoryGroupHtml(group){'),html.indexOf('function renderRepresentativeHistory(){'));
const representativeProfileRender = html.slice(html.indexOf('function representativeProfileHtml(group){'),html.indexOf('function representativeNoteWorkspaceHtml(group,canCreate){'));
const noteEditor = html.slice(html.indexOf('function representativeNoteEditorPanelHtml('),html.indexOf('function openRepresentativeProductsEditor('));
const productsEditor = html.slice(html.indexOf('function representativeProductsEditorModalHtml(){'),html.indexOf('function representativeEditorModalHtml(){'));

assert.match(baseMigration, /alter table public\.notes[\s\S]*representative_id bigint[\s\S]*product_id bigint[\s\S]*activity_type text/);
assert.match(baseMigration, /create trigger audit_notes_changes/);
assert.match(multiProductMigration, /create table public\.representative_activity_items/);
assert.match(multiProductMigration, /create or replace function public\.save_representative_activity/);

assert.match(managedProductsMigration, /create table public\.sales_representative_products/);
assert.match(managedProductsMigration, /primary key \(representative_id,product_id\)/);
assert.match(managedProductsMigration, /sales_representative_products_product_rep_idx/);
assert.match(managedProductsMigration, /alter table public\.sales_representative_products enable row level security/);
assert.match(managedProductsMigration, /create policy sales_representative_products_read/);
assert.match(managedProductsMigration, /representative_activity_items item[\s\S]*on conflict \(representative_id,product_id\) do nothing/);
assert.match(managedProductsMigration, /create or replace function public\.save_representative_note/);
assert.match(managedProductsMigration, /security definer[\s\S]*set search_path = ''/);
assert.match(managedProductsMigration, /for update[\s\S]*p_expected_updated_at/);
assert.match(managedProductsMigration, /delete from public\.sales_representative_products[\s\S]*insert into public\.sales_representative_products/);
assert.match(managedProductsMigration, /delete from public\.representative_activity_items/);
assert.match(managedProductsMigration, /revoke all on function public\.save_representative_note/);
assert.match(separatedEditorsMigration, /create or replace function public\.save_representative_products/);
assert.match(separatedEditorsMigration, /security definer[\s\S]*set search_path = ''/);
assert.match(separatedEditorsMigration, /delete from public\.sales_representative_products[\s\S]*insert into public\.sales_representative_products/);
assert.match(separatedEditorsMigration, /revoke all on function public\.save_representative_products\(bigint,jsonb\)[\s\S]*grant execute[\s\S]*authenticated,service_role/);
assert.doesNotMatch(separatedEditorsMigration.slice(0,separatedEditorsMigration.indexOf('create or replace function public.save_representative_products')), /delete from public\.sales_representative_products/);

assert.match(html, /function renderRepresentativeHistory\(\)/);
assert.match(html, /function renderRepresentativeHistoryOverview\(\)/);
assert.match(html, /function loadRepresentativeActivityHistory\(/);
assert.match(html, /sb\.from\('sales_representative_products'\)/);
assert.match(html, /function representativeHistoryGroups\(\)/);
assert.match(html, /function representativeHistoryGroupHtml\(/);
assert.match(html, /function representativeProfileHtml\(/);
assert.match(html, /function representativeNoteWorkspaceHtml\(/);
assert.match(html, /data-representative-card-open=/);
assert.match(html, /data-product-representative-history=/);
assert.match(html, /\['representativehistory','ผู้แทน'/);
assert.match(html, /representativehistory: renderRepresentativeHistoryOverview/);
const navSource = html.slice(html.indexOf('const NAV = ['),html.indexOf('function renderSidebar()'));
const contactsNavIndex = navSource.indexOf("['contacts','ลูกค้า / ผู้จำหน่าย'");
const representativeNavIndex = navSource.indexOf("['representativehistory','ผู้แทน'");
const contactsSectionIndex = navSource.indexOf("{section:'สมุดรายชื่อ'");
const salesDocumentsSectionIndex = navSource.indexOf("{section:'เอกสารขาย'");
assert.ok(contactsSectionIndex>=0&&contactsNavIndex>contactsSectionIndex&&representativeNavIndex>contactsNavIndex&&representativeNavIndex<salesDocumentsSectionIndex,'เมนูผู้แทนต้องอยู่ใต้ลูกค้า / ผู้จำหน่าย');

assert.match(historyRender, /id="representativeHistoryRepresentativeSearch"/);
assert.match(historyRender, /id="representativeHistoryProductSearch"/);
assert.match(historyRender, /id="representativeHistoryNoteSearch"/);
assert.match(historyRender, /ค้นหาจาก NOTE/);
assert.doesNotMatch(historyRender, /representative-history-summary|NOTE ทั้งหมด/);
assert.doesNotMatch(historyRender, /representativeHistoryTypeFilter|ทุกประเภท|โปรโมชั่นที่ยังใช้ได้|ถึงกำหนดติดตาม/);
assert.match(html, /\.representative-groups-grid\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(html, /\.representative-history-page\{width:100%;max-width:none;margin:0;\}/);
assert.match(html, /data-open-representative-history=/);
assert.match(html, /data-open-product-history=/);
assert.doesNotMatch(historyGroupRender, /รายการสินค้าที่ดูแลมี|representative-managed-products/);
assert.match(html, /\.representative-notes-list\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(html, /\.representative-note-body\{display:-webkit-box;[^}]*overflow:hidden;[^}]*-webkit-line-clamp:4;/);
assert.match(html, /NOTE \$\{index\+1\} :/);
assert.match(html, /\.representative-profile-panel\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(representativeProfileRender, /ชื่อผู้แทน[\s\S]*คลิกเพื่อดูสินค้าที่ผู้แทนดูแล[\s\S]*เบอร์โทร[\s\S]*ไลน์[\s\S]*บริษัท[\s\S]*ข้อมูลเพิ่มเติม/);
assert.doesNotMatch(representativeProfileRender, /field\('สินค้าที่ดูแล'/);
assert.match(html, /\.representative-profile-field\{display:flex;[^}]*justify-content:center;[^}]*text-align:center;/);
assert.match(historyRender, /pagehead topbar-action-source representative-detail-pagehead/);
assert.match(html, /\.representative-note-workspace\{display:grid;grid-template-columns:minmax\(270px,340px\) minmax\(0,1fr\)/);
assert.match(html, /data-select-representative-note=/);
assert.match(html, /representative-note-list-panel[\s\S]*representative-note-inline-editor/);
assert.match(noteEditor, /id="representativeNoteEditorForm"/);
assert.match(noteEditor, /dmyDateFieldHtml\('repActivityEventDate'/);
assert.doesNotMatch(noteEditor, /id="repActivityEventDate" type="date"/);
assert.match(noteEditor, /id="repActivityTitle"/);
assert.match(noteEditor, /id="repActivityContentEditor"[\s\S]*contenteditable=/);
assert.match(noteEditor, /data-representative-note-command="bold"/);
assert.match(noteEditor, /data-representative-note-command="underline"/);
assert.match(noteEditor, /data-representative-note-command="strikeThrough"/);
assert.match(noteEditor, /data-representative-note-color=/);
assert.doesNotMatch(noteEditor, /<textarea id="repActivityContent"/);
assert.doesNotMatch(noteEditor, /repActivityRepresentative|representativeManagedProductSearch|repActivityType|repActivityValidFrom|repActivityValidTo|repActivityReminderDate|quotedPrice|minimumQuantity|conditionNote/);
assert.match(html, /NOTE \$\{index\+1\} : \$\{escapeHtml\(note\.title\|\|'-'\)\}[\s\S]*วันที่/);
assert.doesNotMatch(html, /data-edit-representative-activity=/);
assert.match(productsEditor, /id="representativeProductsSearch"/);
assert.match(productsEditor, /id="representativeProductsDropdown"/);
assert.match(productsEditor, /id="representativeProductsSelectedList"/);
assert.match(productsEditor, /id="saveRepresentativeProductsBtn"/);
assert.match(html, /data-add-representative-product=/);
assert.match(html, /\.slice\(0,12\)/);
assert.match(html, /representative-product-selected-card/);
assert.doesNotMatch(productsEditor, /รายการสินค้า|representativeProductsOptions|แสดงสูงสุด/);
assert.match(html, /คลิกเพื่อดูสินค้าที่ผู้แทนดูแล/);
assert.doesNotMatch(html, /กดเพื่อดู เพิ่ม หรือลบสินค้า/);
assert.match(html, /data-manage-representative-products=/);
assert.match(html, /function representativeEditorModalHtml\(\)/);
assert.match(historyRender, /id="newSalesRepBtn"/);
assert.match(historyRender, /\+ เพิ่มโน้ต/);
assert.doesNotMatch(historyRender, /\+ เพิ่มประวัติ|representativeActivityFormHtml/);
assert.match(html, /sb\.rpc\('save_representative_note',rpcPayload\)/);
assert.match(html, /eventDate:dmyToISO\(value\('repActivityEventDate'\)\)\|\|''/);
assert.match(html, /p_product_ids:\[\]/);
assert.match(html, /sb\.rpc\('save_representative_products'/);
assert.doesNotMatch(html, /function representativeActivityFormHtml\(\)/);
assert.doesNotMatch(html, /\['salesreps','รายชื่อผู้แทน'/);
assert.match(html, /notes:'NOTE \/ ผู้แทน'/);

console.log('representative activity history tests passed');
