const assert = require('node:assert/strict');
const source = require('./load-app-source')();

assert.doesNotMatch(source, /ใช้ราคาพิเศษที่ตั้งไว้โดยอัตโนมัติ/);
const formStart = source.indexOf('function renderShortageOrderForm');
const formEnd = source.indexOf('function renderProductReturnForm', formStart);
const form = source.slice(formStart, formEnd);
const listStart=source.indexOf('function renderPurchaseOrder()');
const listEnd=source.indexOf('function poUnitOptions(',listStart);
const listSource=source.slice(listStart,listEnd);
const toolbarStart=source.indexOf('function documentBulkToolbar(');
const toolbarEnd=source.indexOf('function expiryBadge(',toolbarStart);
const toolbarSource=source.slice(toolbarStart,toolbarEnd);
const printStart=source.indexOf('function printPO(');
const printEnd=source.indexOf('// แปลงตัวเลขเป็นข้อความภาษาไทย',printStart);
const printSource=source.slice(printStart,printEnd);
assert.match(form, /shortage-form-grid[\s\S]*shortage-form-main[\s\S]*shortage-rep-summary/);
assert.match(source, /\.shortage-form-grid\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/, 'ข้อมูลผู้แทนต้องกว้างครึ่งหนึ่งของพื้นที่ส่วนบน');
assert.match(source, /\.shortage-form-controls\{[^}]*grid-template-columns:240px minmax\(0,1fr\) auto auto/, 'คอลัมน์วันที่ต้องพอดีกับช่องเพื่อให้ชื่อผู้แทนใช้พื้นที่ว่าง');
assert.match(source, /\.shortage-form-grid \.shortage-date-field \.dmy-input\{[^}]*width:100%/, 'ช่องพิมพ์วันที่ต้องยาวถึงไอคอนปฏิทิน');
assert.match(source, /\.shortage-form-grid \.shortage-date-field \.dmy-native\{[^}]*width:30px/, 'ปุ่มปฏิทินต้องไม่ซ้อนทับพื้นที่พิมพ์วันที่');
assert.match(form, /วันที่สั่ง[\s\S]*ชื่อผู้แทน[\s\S]*id="newPORepBtn"[\s\S]*id="shortageManagedProductsBtn"/);
assert.match(form, /class="btn primary" id="shortageManagedProductsBtn"/, 'ปุ่มสินค้าที่ดูแลต้องใช้สีเดียวกับปุ่มบันทึกเอกสาร');
assert.doesNotMatch(form, /createPurchaseOrderFromShortageBtn|สร้างใบสั่งซื้อจากรายการนี้/, 'หน้าสั่งซื้อสินค้าต้องเป็นระบบเดียวและไม่มีขั้นตอนแปลงเอกสารซ้ำ');
assert.match(form, /สั่งซื้อสินค้า ›/);
assert.match(form, /shortage-note-field[\s\S]*หมายเหตุ/);
assert.doesNotMatch(form, /id="editPORepBtn"/, 'หน้าสั่งซื้อสินค้าต้องไม่มีปุ่มแก้ไขข้างชื่อผู้แทน');
assert.match(source, /from\('sales_representative_products'\)[\s\S]{0,220}\.eq\('representative_id',Number\(representative\.id\)\)/);
assert.match(source, /data-shortage-managed-product=/);
assert.match(source, /addDocumentScannedProduct\(product\.id,product\.unit\)/);
assert.doesNotMatch(source, /function createPurchaseOrderFromShortage\(\)/);
assert.match(listSource, /data-act="editpo"[\s\S]*data-act="printpo"/, 'ไอคอนพิมพ์ต้องอยู่หลังไอคอนแก้ไขในแต่ละเอกสาร');
const toolbar=require('node:vm').runInNewContext(`(${toolbarSource})`);
for(const kind of ['po','ret','quotation']) assert.doesNotMatch(toolbar(kind),/id="docBulkPrint"/,'หน้าสั่งซื้อ คืนสินค้า และใบเสนอราคาต้องไม่มีปุ่มพิมพ์หลายรายการ');
assert.match(toolbar('gr'),/id="docBulkPrint"/,'หน้ารับเข้าสินค้ายังคงมีปุ่มพิมพ์หลายรายการ');
assert.match(printSource, /ข้อมูลผู้แทน[\s\S]*ชื่อ <b>[\s\S]*บริษัท <b>/, 'เอกสารพิมพ์ต้องแสดงเฉพาะชื่อและบริษัทของผู้แทน');
assert.doesNotMatch(printSource, /เบอร์โทร \$\{escapeHtml\(supplier\?\.phone|ไลน์ \$\{escapeHtml\(supplier\?\.line|supplier\?\.note/, 'เอกสารพิมพ์ต้องไม่แสดงเบอร์โทร ไลน์ หรือข้อมูลเพิ่มเติมของผู้แทน');
assert.doesNotMatch(printSource, /<b>หมายเหตุ:<\/b>/, 'เอกสารสั่งซื้อสินค้าต้องไม่มีหมายเหตุท้ายกระดาษ');
assert.doesNotMatch(printSource, /styled\?'ผู้ขาย':'ผู้แทน'|styled\?'ผู้รับสินค้า':'ผู้อนุมัติ'/, 'เอกสารสั่งซื้อสินค้าต้องไม่มีช่องลงชื่อผู้แทนและผู้อนุมัติ');

console.log('shortage managed products tests passed');
