const fs = require('node:fs');
const path = require('node:path');
const { Script } = require('node:vm');

const projectRoot = path.resolve(__dirname, '..');
const generatedHeader = '// GENERATED by scripts/app-source.cjs. Edit src/ files, never this file.\n';

// Ordered classic-script composition intentionally preserves legacy shared scope,
// function hoisting and startup order. Do not load these files as separate scripts
// or wrap them in modules until their state dependencies have been made explicit.
function sourceFiles(root = projectRoot) {
  const files = JSON.parse(fs.readFileSync(path.join(root, 'src/source-manifest.json'), 'utf8'));
  if (!Array.isArray(files) || !files.length || new Set(files).size !== files.length) throw new Error('Invalid/duplicate application source manifest');
  for (const file of files) {
    if (typeof file !== 'string' || !/^src\/(?:[a-z-]+\/)+[a-z-]+\.js$/.test(file)) throw new Error(`Unsafe source path: ${file}`);
  }
  return files;
}

function readApplicationSource(root = projectRoot) {
  return sourceFiles(root).map(file => {
    const source = fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n');
    new Script(source, { filename: file });
    return source.endsWith('\n') ? source : source + '\n';
  }).join('');
}

function writeDevelopmentApp() {
  const source = generatedHeader + readApplicationSource();
  new Script(source, { filename: 'app.js' });
  const target = path.join(projectRoot, 'app.js');
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== source) fs.writeFileSync(target, source);
  return source;
}

module.exports = { projectRoot, sourceFiles, readApplicationSource, writeDevelopmentApp };
if (require.main === module) {
  writeDevelopmentApp();
  console.log('Prepared development app.js from src/source-manifest.json');
}
