-- Allow the app to upsert explicit id values (matching the client-side
-- integer ids already used for products/warehouses) instead of only
-- auto-generated ones.
alter table public.products alter column id set generated by default;
alter table public.warehouses alter column id set generated by default;

-- Same fix, extended to contacts and sales_representatives.
alter table public.contacts alter column id set generated by default;
alter table public.sales_representatives alter column id set generated by default;
