-- Lot-aware inventory. inventory_balances remains the fast summary used by
-- existing screens, while inventory_lots is the quantity/expiry authority.

create table if not exists public.inventory_lots (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  warehouse_id bigint not null references public.warehouses(id) on delete restrict,
  internal_code text not null unique,
  manufacturer_lot text,
  expiry_date date,
  quantity_base numeric not null default 0 check (quantity_base >= 0),
  unit_cost_base numeric not null default 0 check (unit_cost_base >= 0),
  received_at timestamptz not null default now(),
  source_type text not null default 'opening',
  source_id text,
  source_line_key text,
  status text not null default 'active' check (status in ('active','blocked','exhausted')),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_inventory_lots_fefo
on public.inventory_lots(warehouse_id,product_id,status,expiry_date,received_at,id)
where quantity_base > 0;

create index if not exists idx_inventory_lots_product
on public.inventory_lots(product_id,warehouse_id,updated_at desc);

create index if not exists idx_inventory_lots_manufacturer
on public.inventory_lots(manufacturer_lot)
where manufacturer_lot is not null;

create unique index if not exists idx_inventory_lots_source
on public.inventory_lots(source_type,source_id,source_line_key)
where source_id is not null and source_line_key is not null;

create table if not exists public.inventory_lot_movements (
  id bigint generated always as identity primary key,
  lot_id bigint not null references public.inventory_lots(id) on delete restrict,
  product_id bigint not null references public.products(id) on delete restrict,
  warehouse_id bigint not null references public.warehouses(id) on delete restrict,
  movement_type text not null,
  quantity_delta numeric not null check (quantity_delta <> 0),
  balance_after numeric not null check (balance_after >= 0),
  reference_type text,
  reference_id text,
  reference_line_key text,
  note text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_lot_movements_lot
on public.inventory_lot_movements(lot_id,created_at desc);

create index if not exists idx_inventory_lot_movements_reference
on public.inventory_lot_movements(reference_type,reference_id,created_at desc);

create index if not exists idx_inventory_lot_movements_product_warehouse
on public.inventory_lot_movements(product_id,warehouse_id,created_at desc);

create unique index if not exists idx_inventory_lot_movements_once
on public.inventory_lot_movements(reference_type,reference_id,reference_line_key,lot_id,movement_type)
where reference_id is not null and reference_line_key is not null;

alter table public.inventory_lots enable row level security;
alter table public.inventory_lot_movements enable row level security;
revoke all on public.inventory_lots from anon,authenticated;
revoke all on public.inventory_lot_movements from anon,authenticated;
grant select on public.inventory_lots to authenticated;
grant select on public.inventory_lot_movements to authenticated;
grant all on public.inventory_lots to service_role;
grant all on public.inventory_lot_movements to service_role;

drop policy if exists inventory_lots_read_accessible_warehouse on public.inventory_lots;
create policy inventory_lots_read_accessible_warehouse on public.inventory_lots
for select to authenticated using (
  (select private.is_current_owner()) or exists (
    select 1 from public.profile_warehouse_access access
    where access.user_id=(select auth.uid())
      and access.warehouse_id=inventory_lots.warehouse_id
      and access.can_sell
  )
);

drop policy if exists inventory_lot_movements_read_accessible_warehouse on public.inventory_lot_movements;
create policy inventory_lot_movements_read_accessible_warehouse on public.inventory_lot_movements
for select to authenticated using (
  (select private.is_current_owner()) or exists (
    select 1 from public.profile_warehouse_access access
    where access.user_id=(select auth.uid())
      and access.warehouse_id=inventory_lot_movements.warehouse_id
      and access.can_sell
  )
);

create or replace function private.refresh_inventory_balance_from_lots(
  p_product_id bigint,
  p_warehouse_id bigint
) returns numeric
language plpgsql security definer set search_path=''
as $$
declare v_stock numeric; v_expiry date;
begin
  select coalesce(sum(lot.quantity_base),0),min(lot.expiry_date)
  into v_stock,v_expiry
  from public.inventory_lots lot
  where lot.product_id=p_product_id and lot.warehouse_id=p_warehouse_id
    and lot.status<>'blocked' and lot.quantity_base>0;

  insert into public.inventory_balances(warehouse_id,product_id,stock,expiry,updated_at)
  values(p_warehouse_id,p_product_id,v_stock,v_expiry,now())
  on conflict (warehouse_id,product_id) do update
    set stock=excluded.stock,expiry=excluded.expiry,updated_at=now();

  update public.products set stock=v_stock,updated_at=now()
  where id=p_product_id and warehouse_id=p_warehouse_id;
  return v_stock;
end;
$$;

create or replace function private.create_inventory_lot(
  p_product_id bigint,
  p_warehouse_id bigint,
  p_quantity numeric,
  p_manufacturer_lot text,
  p_expiry date,
  p_unit_cost numeric,
  p_source_type text,
  p_source_id text,
  p_source_line_key text,
  p_received_at timestamptz default now()
) returns bigint
language plpgsql security definer set search_path=''
as $$
declare v_id bigint; v_code text;
begin
  if coalesce(p_quantity,0)<=0 then raise exception 'lot quantity must be positive'; end if;
  if p_source_id is not null and p_source_line_key is not null then
    select id into v_id from public.inventory_lots
    where source_type=p_source_type and source_id=p_source_id and source_line_key=p_source_line_key;
    if v_id is not null then return v_id; end if;
  end if;
  v_code:='LOT-'||upper(coalesce(nullif(regexp_replace(coalesce(p_source_id,p_source_type),'[^A-Za-z0-9]','','g'),''),'AUTO'))||'-'||substr(replace(gen_random_uuid()::text,'-',''),1,8);
  insert into public.inventory_lots(product_id,warehouse_id,internal_code,manufacturer_lot,expiry_date,quantity_base,unit_cost_base,received_at,source_type,source_id,source_line_key,status)
  values(p_product_id,p_warehouse_id,v_code,nullif(btrim(p_manufacturer_lot),''),p_expiry,p_quantity,greatest(coalesce(p_unit_cost,0),0),coalesce(p_received_at,now()),coalesce(nullif(p_source_type,''),'manual'),p_source_id,p_source_line_key,'active')
  returning id into v_id;
  return v_id;
end;
$$;

revoke execute on function private.refresh_inventory_balance_from_lots(bigint,bigint) from public,anon,authenticated;
revoke execute on function private.create_inventory_lot(bigint,bigint,numeric,text,date,numeric,text,text,text,timestamptz) from public,anon,authenticated;

-- Preserve every existing positive warehouse balance as one opening lot.
insert into public.inventory_lots(product_id,warehouse_id,internal_code,manufacturer_lot,expiry_date,quantity_base,unit_cost_base,received_at,source_type,source_id,source_line_key,status)
select balance.product_id,balance.warehouse_id,
       'OPEN-'||balance.warehouse_id||'-'||balance.product_id,
       null,balance.expiry,balance.stock,coalesce(product.cost,0),coalesce(product.created_at,now()),
       'opening','inventory-lot-migration',balance.warehouse_id||':'||balance.product_id,'active'
from public.inventory_balances balance
join public.products product on product.id=balance.product_id
where balance.stock>0
on conflict do nothing;

insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
select lot.id,lot.product_id,lot.warehouse_id,'opening',lot.quantity_base,lot.quantity_base,
       'migration','inventory-lot-migration',lot.warehouse_id||':'||lot.product_id,'ยอดยกมาก่อนเริ่มใช้ระบบ Lot'
from public.inventory_lots lot
where lot.source_type='opening' and lot.source_id='inventory-lot-migration'
on conflict do nothing;

create or replace function public.apply_goods_receipt_lots(p_receipt_id text)
returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  v_row public.goods_receipts%rowtype; v_data jsonb; v_item jsonb; v_lots jsonb:='[]'::jsonb;
  v_warehouse bigint; v_product bigint; v_qty numeric; v_factor numeric; v_cost numeric;
  v_expiry date; v_lot_number text; v_line_key text; v_lot_id bigint; v_ord bigint; v_stock numeric;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  select * into v_row from public.goods_receipts where id=p_receipt_id for update;
  if not found then raise exception 'goods receipt not found'; end if;
  v_data:=coalesce(v_row.data,'{}'::jsonb);
  v_warehouse:=nullif(v_data->>'warehouseId','')::bigint;
  if v_warehouse is null then raise exception 'warehouse is required'; end if;
  if not (select private.is_current_owner()) and not exists (
    select 1 from public.profile_warehouse_access access
    where access.user_id=(select auth.uid()) and access.warehouse_id=v_warehouse and access.can_manage_stock
  ) then raise exception 'stock management access denied'; end if;
  if coalesce(v_data->>'lotAppliedAt','')<>'' then return jsonb_build_object('receipt',v_data,'lots',v_lots); end if;
  if coalesce((v_data->>'stockApplied')::boolean,false) then
    -- Legacy receipts are already represented by their opening lot.
    return jsonb_build_object('receipt',v_data,'lots',v_lots,'legacy',true);
  end if;

  for v_item,v_ord in
    select value,ordinality from jsonb_array_elements(coalesce(v_data->'items','[]'::jsonb)) with ordinality
  loop
    v_product:=nullif(v_item->>'productId','')::bigint;
    v_factor:=greatest(coalesce(nullif(v_item->>'stockFactor','')::numeric,1),0);
    v_qty:=coalesce(nullif(v_item->>'qty','')::numeric,0)*v_factor;
    if v_product is null or v_qty<=0 then raise exception 'invalid goods receipt item %',v_ord; end if;
    v_line_key:=coalesce(nullif(v_item->>'lineId',''),v_ord::text);
    v_lot_number:=nullif(btrim(coalesce(v_item->>'lotNumber','')),'');
    v_expiry:=case when coalesce(v_item->>'expiry','')~'^\d{4}-\d{2}-\d{2}$' then (v_item->>'expiry')::date else null end;
    v_cost:=case when v_factor>0 then coalesce(nullif(v_item->>'price','')::numeric,0)/v_factor else 0 end;
    v_lot_id:=private.create_inventory_lot(v_product,v_warehouse,v_qty,v_lot_number,v_expiry,v_cost,'goods_receipt',p_receipt_id,v_line_key,coalesce(v_row.created_at,now()));
    insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
    select v_lot_id,v_product,v_warehouse,'receive',v_qty,lot.quantity_base,'goods_receipt',p_receipt_id,v_line_key,'รับเข้าสินค้า'
    from public.inventory_lots lot where lot.id=v_lot_id
    on conflict do nothing;
    v_stock:=private.refresh_inventory_balance_from_lots(v_product,v_warehouse);
    v_lots:=v_lots||jsonb_build_array(jsonb_build_object('lineKey',v_line_key,'lotId',v_lot_id,'stock',v_stock));
  end loop;
  v_data:=jsonb_set(v_data,'{status}',to_jsonb('รับสินค้าแล้ว'::text),true);
  v_data:=jsonb_set(v_data,'{stockApplied}','true'::jsonb,true);
  v_data:=jsonb_set(v_data,'{stockAppliedAt}',to_jsonb(now()::text),true);
  v_data:=jsonb_set(v_data,'{lotAppliedAt}',to_jsonb(now()::text),true);
  update public.goods_receipts set data=v_data,updated_at=now() where id=p_receipt_id;
  return jsonb_build_object('receipt',v_data,'lots',v_lots);
end;
$$;

create or replace function public.post_sale_inventory_lots(
  p_sale_id text,
  p_warehouse_id bigint,
  p_items jsonb
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  v_item jsonb; v_ord bigint; v_product bigint; v_need numeric; v_take numeric; v_line_key text;
  v_lot record; v_allocations jsonb:='[]'::jsonb; v_balances jsonb:='[]'::jsonb; v_stock numeric;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  if p_sale_id is null or p_warehouse_id is null then raise exception 'sale and warehouse are required'; end if;
  if not (select private.is_current_owner()) and not exists (
    select 1 from public.profile_warehouse_access access
    where access.user_id=(select auth.uid()) and access.warehouse_id=p_warehouse_id and access.can_sell
  ) then raise exception 'warehouse sale access denied'; end if;

  if exists (select 1 from public.inventory_lot_movements where reference_type='sale' and reference_id=p_sale_id) then
    select coalesce(jsonb_agg(jsonb_build_object(
      'lineKey',movement.reference_line_key,'productId',movement.product_id,'lotId',lot.id,
      'internalCode',lot.internal_code,'lotNumber',lot.manufacturer_lot,'expiry',lot.expiry_date,
      'baseQty',abs(movement.quantity_delta),'unitCostBase',lot.unit_cost_base
    ) order by movement.id),'[]'::jsonb)
    into v_allocations
    from public.inventory_lot_movements movement join public.inventory_lots lot on lot.id=movement.lot_id
    where movement.reference_type='sale' and movement.reference_id=p_sale_id;
    return jsonb_build_object('allocations',v_allocations,'alreadyApplied',true);
  end if;

  for v_item,v_ord in select value,ordinality from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) with ordinality loop
    if coalesce((v_item->>'custom')::boolean,false) then continue; end if;
    v_product:=nullif(v_item->>'productId','')::bigint;
    v_need:=coalesce(nullif(v_item->>'baseQty','')::numeric,
      coalesce(nullif(v_item->>'qty','')::numeric,0)*coalesce(nullif(v_item->>'factor','')::numeric,1));
    v_line_key:=coalesce(nullif(v_item->>'lineKey',''),v_ord::text);
    if v_product is null or v_need<=0 then raise exception 'invalid sale item %',v_ord; end if;

    for v_lot in
      select * from public.inventory_lots lot
      where lot.product_id=v_product and lot.warehouse_id=p_warehouse_id
        and lot.status='active' and lot.quantity_base>0
        and (lot.expiry_date is null or lot.expiry_date>=current_date)
      order by lot.expiry_date asc nulls last,lot.received_at,lot.id
      for update
    loop
      exit when v_need<=0;
      v_take:=least(v_need,v_lot.quantity_base);
      update public.inventory_lots
      set quantity_base=quantity_base-v_take,status=case when quantity_base-v_take<=0 then 'exhausted' else 'active' end,updated_at=now()
      where id=v_lot.id;
      insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
      values(v_lot.id,v_product,p_warehouse_id,'sale',-v_take,v_lot.quantity_base-v_take,'sale',p_sale_id,v_line_key,'ขายสินค้า');
      v_allocations:=v_allocations||jsonb_build_array(jsonb_build_object(
        'lineKey',v_line_key,'productId',v_product,'lotId',v_lot.id,'internalCode',v_lot.internal_code,
        'lotNumber',v_lot.manufacturer_lot,'expiry',v_lot.expiry_date,'baseQty',v_take,'unitCostBase',v_lot.unit_cost_base));
      v_need:=v_need-v_take;
    end loop;
    if v_need>0 then raise exception 'insufficient non-expired lot stock for product %',v_product; end if;
    v_stock:=private.refresh_inventory_balance_from_lots(v_product,p_warehouse_id);
    v_balances:=v_balances||jsonb_build_array(jsonb_build_object('productId',v_product,'warehouseId',p_warehouse_id,'stock',v_stock));
  end loop;
  return jsonb_build_object('allocations',v_allocations,'balances',v_balances,'alreadyApplied',false);
end;
$$;

create or replace function public.adjust_inventory_stock(
  p_product_id bigint, p_warehouse_id bigint, p_delta numeric
) returns numeric
language plpgsql security definer set search_path=''
as $$
declare v_delta numeric:=coalesce(p_delta,0); v_need numeric; v_take numeric; v_lot record; v_lot_id bigint; v_ref text; v_stock numeric; v_expiry date; v_cost numeric;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  if not (select private.is_current_owner()) and not exists (
    select 1 from public.profile_warehouse_access access where access.user_id=(select auth.uid()) and access.warehouse_id=p_warehouse_id and (access.can_sell or access.can_manage_stock)
  ) then raise exception 'warehouse access denied'; end if;
  if v_delta=0 then return private.refresh_inventory_balance_from_lots(p_product_id,p_warehouse_id); end if;
  v_ref:='ADJ-'||replace(gen_random_uuid()::text,'-','');
  if v_delta>0 then
    select expiry into v_expiry from public.inventory_balances where product_id=p_product_id and warehouse_id=p_warehouse_id;
    select coalesce(cost,0) into v_cost from public.products where id=p_product_id;
    v_lot_id:=private.create_inventory_lot(p_product_id,p_warehouse_id,v_delta,null,v_expiry,v_cost,'adjustment',v_ref,'1',now());
    insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
    values(v_lot_id,p_product_id,p_warehouse_id,'adjustment',v_delta,v_delta,'adjustment',v_ref,'1','ปรับเพิ่มสต๊อก');
  else
    v_need:=abs(v_delta);
    for v_lot in select * from public.inventory_lots lot
      where lot.product_id=p_product_id and lot.warehouse_id=p_warehouse_id and lot.status<>'blocked' and lot.quantity_base>0
      order by lot.expiry_date asc nulls last,lot.received_at,lot.id for update
    loop
      exit when v_need<=0;
      v_take:=least(v_need,v_lot.quantity_base);
      update public.inventory_lots set quantity_base=quantity_base-v_take,status=case when quantity_base-v_take<=0 then 'exhausted' else status end,updated_at=now() where id=v_lot.id;
      insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
      values(v_lot.id,p_product_id,p_warehouse_id,'adjustment',-v_take,v_lot.quantity_base-v_take,'adjustment',v_ref,v_lot.id::text,'ปรับลดสต๊อก');
      v_need:=v_need-v_take;
    end loop;
    if v_need>0 then raise exception 'insufficient lot stock for product %',p_product_id; end if;
  end if;
  v_stock:=private.refresh_inventory_balance_from_lots(p_product_id,p_warehouse_id);
  return v_stock;
end;
$$;

create or replace function public.set_inventory_stock(
  p_product_id bigint, p_warehouse_id bigint, p_stock numeric
) returns numeric
language plpgsql security definer set search_path=''
as $$
declare v_current numeric; v_target numeric:=coalesce(p_stock,0);
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  if v_target<0 then raise exception 'stock must not be negative'; end if;
  if not (select private.is_current_owner()) and not exists (
    select 1 from public.profile_warehouse_access access where access.user_id=(select auth.uid()) and access.warehouse_id=p_warehouse_id and access.can_manage_stock
  ) then raise exception 'stock management access denied'; end if;
  insert into public.inventory_balances(warehouse_id,product_id,stock,updated_at) values(p_warehouse_id,p_product_id,0,now()) on conflict do nothing;
  select stock into v_current from public.inventory_balances where warehouse_id=p_warehouse_id and product_id=p_product_id for update;
  if v_target=coalesce(v_current,0) then return v_target; end if;
  return public.adjust_inventory_stock(p_product_id,p_warehouse_id,v_target-coalesce(v_current,0));
end;
$$;

create or replace function public.set_inventory_expiry(
  p_product_id bigint, p_warehouse_id bigint, p_expiry date
) returns date
language plpgsql security definer set search_path=''
as $$
declare v_lot_id bigint;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  if not (select private.is_current_owner()) and not exists (
    select 1 from public.profile_warehouse_access access where access.user_id=(select auth.uid()) and access.warehouse_id=p_warehouse_id and access.can_manage_stock
  ) then raise exception 'stock management access denied'; end if;
  select id into v_lot_id from public.inventory_lots
  where product_id=p_product_id and warehouse_id=p_warehouse_id and status<>'blocked' and quantity_base>0
  order by expiry_date asc nulls last,received_at,id limit 1 for update;
  if v_lot_id is not null then
    update public.inventory_lots set expiry_date=p_expiry,updated_at=now() where id=v_lot_id;
    perform private.refresh_inventory_balance_from_lots(p_product_id,p_warehouse_id);
  else
    insert into public.inventory_balances(warehouse_id,product_id,stock,expiry,updated_at)
    values(p_warehouse_id,p_product_id,0,p_expiry,now())
    on conflict (warehouse_id,product_id) do update set expiry=excluded.expiry,updated_at=now();
  end if;
  return p_expiry;
end;
$$;

create or replace function public.update_inventory_lot_details(
  p_lot_id bigint,p_manufacturer_lot text,p_expiry date
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_lot public.inventory_lots%rowtype;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  select * into v_lot from public.inventory_lots where id=p_lot_id for update;
  if not found then raise exception 'lot not found'; end if;
  if not (select private.is_current_owner()) and not exists (
    select 1 from public.profile_warehouse_access access where access.user_id=(select auth.uid()) and access.warehouse_id=v_lot.warehouse_id and access.can_manage_stock
  ) then raise exception 'stock management access denied'; end if;
  update public.inventory_lots set manufacturer_lot=nullif(btrim(p_manufacturer_lot),''),expiry_date=p_expiry,updated_at=now() where id=p_lot_id returning * into v_lot;
  perform private.refresh_inventory_balance_from_lots(v_lot.product_id,v_lot.warehouse_id);
  return to_jsonb(v_lot);
end;
$$;

create or replace function public.transfer_inventory_stock(
  p_product_id bigint,p_from_warehouse_id bigint,p_to_warehouse_id bigint,p_quantity numeric
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_need numeric:=coalesce(p_quantity,0); v_take numeric; v_lot record; v_dest_lot bigint; v_ref text; v_from numeric; v_to numeric; v_alloc jsonb:='[]'::jsonb;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  if not (select private.is_current_owner()) and not (
    exists (select 1 from public.profile_warehouse_access access where access.user_id=(select auth.uid()) and access.warehouse_id=p_from_warehouse_id and access.can_manage_stock)
    and exists (select 1 from public.profile_warehouse_access access where access.user_id=(select auth.uid()) and access.warehouse_id=p_to_warehouse_id and access.can_manage_stock)
  ) then raise exception 'stock transfer access denied'; end if;
  if p_from_warehouse_id=p_to_warehouse_id or v_need<=0 then raise exception 'invalid transfer'; end if;
  v_ref:='TF-'||replace(gen_random_uuid()::text,'-','');
  for v_lot in select * from public.inventory_lots lot
    where lot.product_id=p_product_id and lot.warehouse_id=p_from_warehouse_id and lot.status<>'blocked' and lot.quantity_base>0
    order by lot.expiry_date asc nulls last,lot.received_at,lot.id for update
  loop
    exit when v_need<=0;
    v_take:=least(v_need,v_lot.quantity_base);
    update public.inventory_lots set quantity_base=quantity_base-v_take,status=case when quantity_base-v_take<=0 then 'exhausted' else status end,updated_at=now() where id=v_lot.id;
    insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
    values(v_lot.id,p_product_id,p_from_warehouse_id,'transfer_out',-v_take,v_lot.quantity_base-v_take,'transfer',v_ref,v_lot.id::text,'โอนออก');
    v_dest_lot:=private.create_inventory_lot(p_product_id,p_to_warehouse_id,v_take,v_lot.manufacturer_lot,v_lot.expiry_date,v_lot.unit_cost_base,'transfer',v_ref,v_lot.id::text,now());
    insert into public.inventory_lot_movements(lot_id,product_id,warehouse_id,movement_type,quantity_delta,balance_after,reference_type,reference_id,reference_line_key,note)
    values(v_dest_lot,p_product_id,p_to_warehouse_id,'transfer_in',v_take,v_take,'transfer',v_ref,v_lot.id::text,'โอนเข้า');
    v_alloc:=v_alloc||jsonb_build_array(jsonb_build_object('sourceLotId',v_lot.id,'destinationLotId',v_dest_lot,'baseQty',v_take,'lotNumber',v_lot.manufacturer_lot,'expiry',v_lot.expiry_date));
    v_need:=v_need-v_take;
  end loop;
  if v_need>0 then raise exception 'insufficient source warehouse lot stock'; end if;
  v_from:=private.refresh_inventory_balance_from_lots(p_product_id,p_from_warehouse_id);
  v_to:=private.refresh_inventory_balance_from_lots(p_product_id,p_to_warehouse_id);
  return jsonb_build_object('fromStock',v_from,'toStock',v_to,'allocations',v_alloc);
end;
$$;

create or replace function public.owner_update_mobile_product(
  p_product_id bigint,p_warehouse_id bigint,p_product_data jsonb,p_price numeric,p_cost numeric,p_stock numeric,p_expiry date
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare v_stock numeric; v_expiry date;
begin
  if (select auth.uid()) is null then raise exception 'authentication required'; end if;
  if not (select private.is_current_owner()) then raise exception 'owner access required'; end if;
  if p_product_id is null or p_warehouse_id is null then raise exception 'product and warehouse are required'; end if;
  if coalesce(p_price,0)<0 or coalesce(p_cost,0)<0 or coalesce(p_stock,0)<0 then raise exception 'values must not be negative'; end if;
  update public.products set data=(coalesce(p_product_data,'{}'::jsonb)-'stock'-'_catalogExpiry'),price=coalesce(p_price,0),cost=coalesce(p_cost,0),updated_at=now() where id=p_product_id;
  if not found then raise exception 'product not found'; end if;
  v_stock:=public.set_inventory_stock(p_product_id,p_warehouse_id,p_stock);
  v_expiry:=public.set_inventory_expiry(p_product_id,p_warehouse_id,p_expiry);
  return jsonb_build_object('productId',p_product_id,'warehouseId',p_warehouse_id,'stock',v_stock,'expiry',v_expiry);
end;
$$;

revoke execute on function public.apply_goods_receipt_lots(text) from public,anon;
revoke execute on function public.post_sale_inventory_lots(text,bigint,jsonb) from public,anon;
revoke execute on function public.adjust_inventory_stock(bigint,bigint,numeric) from public,anon;
revoke execute on function public.set_inventory_stock(bigint,bigint,numeric) from public,anon;
revoke execute on function public.set_inventory_expiry(bigint,bigint,date) from public,anon;
revoke execute on function public.update_inventory_lot_details(bigint,text,date) from public,anon;
revoke execute on function public.transfer_inventory_stock(bigint,bigint,bigint,numeric) from public,anon;
revoke execute on function public.owner_update_mobile_product(bigint,bigint,jsonb,numeric,numeric,numeric,date) from public,anon;
grant execute on function public.apply_goods_receipt_lots(text) to authenticated;
grant execute on function public.post_sale_inventory_lots(text,bigint,jsonb) to authenticated;
grant execute on function public.adjust_inventory_stock(bigint,bigint,numeric) to authenticated;
grant execute on function public.set_inventory_stock(bigint,bigint,numeric) to authenticated;
grant execute on function public.set_inventory_expiry(bigint,bigint,date) to authenticated;
grant execute on function public.update_inventory_lot_details(bigint,text,date) to authenticated;
grant execute on function public.transfer_inventory_stock(bigint,bigint,bigint,numeric) to authenticated;
grant execute on function public.owner_update_mobile_product(bigint,bigint,jsonb,numeric,numeric,numeric,date) to authenticated;
